/*
 * generated by Xtext 2.34.0
 */
package dev.algo.parsetest.xtext;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class ArithmeticExprStandaloneSetup extends ArithmeticExprStandaloneSetupGenerated {

	public static void doSetup() {
		new ArithmeticExprStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
